spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user-management
    username: user-management-user
    password: user-management-password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true