spring:
  datasource:
    url: jdbc:mysql://user-management.c5sgo8o4qt95.us-east-1.rds.amazonaws.com/user-management?createDatabaseIfNotExist=true
    username: admin_user
    password: mysql-password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/prod/prod-schema.sql
      data-locations: classpath:sql/prod/prod-data.sql